apiVersion: v1
kind: Service
metadata:
    name: "tstakscluster-14c4"
    labels:
        app: "tstakscluster-14c4"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tstakscluster-14c4"